[workspace]
resolver = "2"
members = [
    "contracts/stream",
    "contracts/zk_verifier",
    "contracts/token_wrapper",
]

[workspace.dependencies]
soroban-sdk = { version = "22.0.0" }
ed25519-dalek = { version = "=2.1.1", default-features = false }

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true
