// Real integration against the actual deployed Stellar testnet contracts — no mocking
// here. See deployments/testnet.json (repo root) for where these addresses come from and
// how to verify them independently on stellar.expert.
import { Client as ContractClient } from '@stellar/stellar-sdk/contract';
import { rpc } from '@stellar/stellar-sdk';
import freighter from '@stellar/freighter-api';

export const NETWORK_PASSPHRASE = 'Test SDF Network ; September 2015';
export const RPC_URL = 'https://soroban-testnet.stellar.org';

export const STREAM_CONTRACT_ID = 'CDEJZ5GPOW5GMDTBMJ2WD7ENPKHBPETZFUGAZ76QMDGHT5LNAEG5TKH7';
export const RANGE_PROOF_VERIFIER_ID = 'CARWCSIHZ7HCXDCCLRN2JX7SYDAKMZXI53M6AGUUXPRLLT3UJ3WIDLIY';
export const NATIVE_TOKEN_ID = 'CDLZFC3SYJYDZT7K67VZ75HPJVIEUVNIXF47ZG2FB2RMQQVU2HHGCYSC';

function hexToBytes(hex: string): Uint8Array {
  const out = new Uint8Array(hex.length / 2);
  for (let i = 0; i < out.length; i++) {
    out[i] = parseInt(hex.substring(i * 2, i * 2 + 2), 16);
  }
  return out;
}

// The one real, precomputed Groth16 proof this demo can submit today. Generated by an
// actual trusted-setup pipeline against the real range_proof.circom circuit — see
// ../circuits/README.md and ../circuits/build/range_proof/{proof.json,public.json}. It
// proves a FIXED amount (5,000,000 stroops = 0.5 XLM) is in range [1, 1_000_000_000].
// General-purpose in-browser proof generation (bundling the circuit's wasm witness
// calculator + snarkjs prover) is real future work, not attempted here — this demo can
// only create a stream of exactly this amount for now.
export const DEMO_STREAM_AMOUNT_STROOPS = 5_000_000n;
const REAL_RANGE_PROOF_HEX =
  '1576394dd31e3810dc98e1fd21ab18aedded58d5a5918eb8719e7285cc6f5c4613a756208462ceddbf4b4dcf46f3e8544b10f1838eb2de2ece5dba021d61a82b2543a7eb2ad496caa3ea17e29f0ff89ba9db63f69c12652d389a6ab584ee6d950e362741df18ca9ba3727de772be461afe17f79de97e562214892a5aeb3a4f592eded200fc7f792efbff1db16b68bffa910df19d68c244fb19812e109d43fb6516b288ee6ccde0aa211f20eb79553038b1c207e24517b791e125389beeb85040044a48c43d7df994c4d5faf4eb943e96dcc3247bfe6d0ee4437e0b11b814121d1d871314e79e7fbe0f9e1170749f441a8c68bfd7caf8ebfeb7ac76af49ba612b';
const REAL_RANGE_PROOF_PUBLIC_INPUTS_HEX = [
  '0000000000000000000000000000000000000000000000000000000000000001',
  '0000000000000000000000000000000000000000000000000000000000000001',
  '000000000000000000000000000000000000000000000000000000003b9aca00',
  '2a50431f0c3168c0be1bbb5405b319c02a868a696b208557af125d46fb3ab4f0',
];
export const REAL_RANGE_PROOF_BYTES = hexToBytes(REAL_RANGE_PROOF_HEX);
export const REAL_RANGE_PROOF_PUBLIC_INPUTS = REAL_RANGE_PROOF_PUBLIC_INPUTS_HEX.map(hexToBytes);

export class FreighterNotDetectedError extends Error {}

export async function connectWallet(): Promise<string> {
  const { isConnected, error: connErr } = await freighter.isConnected();
  if (connErr || !isConnected) {
    throw new FreighterNotDetectedError(
      'Freighter wallet extension not detected. Install it from freighter.app to use real wallet features.'
    );
  }
  const { address, error } = await freighter.requestAccess();
  if (error || !address) {
    throw new Error(error?.message ?? 'Wallet access was not granted.');
  }
  const { network, error: netErr } = await freighter.getNetwork();
  if (netErr) throw new Error(netErr.message ?? 'Could not read wallet network.');
  if (network !== 'TESTNET') {
    throw new Error(`Freighter is set to ${network}, but this app talks to Stellar testnet. Switch networks in Freighter.`);
  }
  return address;
}

async function getClient(contractId: string, publicKey?: string) {
  return ContractClient.from({
    contractId,
    networkPassphrase: NETWORK_PASSPHRASE,
    rpcUrl: RPC_URL,
    publicKey,
    signTransaction: freighter.signTransaction,
  });
}

/** The real, authoritative current time, straight from the network — not the local
 * machine's clock. Trusting `Date.now()` here was a real bug: it silently produced
 * timestamps that were already in the past by the time a transaction actually reached
 * the network, because whatever machine is running this (this dev sandbox measurably,
 * possibly others) has a clock that drifts from real time by more than a small buffer
 * can cover. Computing offsets from the network's own `closeTime` instead makes this
 * correct regardless of local clock drift. */
async function getRealNetworkNowSeconds(): Promise<number> {
  const server = new rpc.Server(RPC_URL);
  const ledger = await server.getLatestLedger();
  return Number(ledger.closeTime);
}

/** Read-only: simulates a real call against the real deployed range_proof verifier with
 * the real proof above. No wallet signature needed — this is exactly the same call
 * `stellar contract invoke ... -- vrfy_prf --send=no` makes, just from the browser. */
export async function verifyRealProofOnChain(): Promise<boolean> {
  const client = await getClient(RANGE_PROOF_VERIFIER_ID);
  const tx = await (client as any).vrfy_prf({
    proof: Buffer.from(REAL_RANGE_PROOF_BYTES),
    public_inputs: REAL_RANGE_PROOF_PUBLIC_INPUTS.map((b) => Buffer.from(b)),
  });
  return tx.result as boolean;
}

export interface OnChainStream {
  sender: string;
  recipient: string;
  token: string;
  total_amount: bigint;
  withdrawn_amount: bigint;
  start_time: bigint;
  cliff_time: bigint;
  end_time: bigint;
  active: boolean;
  cancelable: boolean;
}

/** Real, live create_stream call against the real deployed stream contract, using the one
 * real proof this demo has. Requires a connected wallet — the transaction is genuinely
 * built, simulated, signed by Freighter, and submitted to testnet.
 *
 * Timestamps are computed from the network's own real time (`getRealNetworkNowSeconds`),
 * not the local machine's clock. Trusting `Date.now()` here was a real, measured bug:
 * whatever machine ends up running this can have a clock that drifts from real network
 * time by more than any reasonable fixed buffer, so start_time kept landing in the past
 * by the time the transaction actually reached the network (surfacing as a bare
 * "UnreachableCodeReached" trap, since release wasm strips panic message strings —
 * confirmed by reproducing it standalone against the real contract outside the browser).
 * `timeoutInSeconds` (the signed transaction ENVELOPE's own submission validity window —
 * a separate mechanism from start_time, recomputed by the SDK at the moment signing
 * actually happens) is set generously too, since it's still measured from local time and
 * also needs to cover real human review-and-approve time in Freighter's popup.
 */
export async function createRealDemoStream(senderPublicKey: string, recipient: string): Promise<number> {
  const client = await getClient(STREAM_CONTRACT_ID, senderPublicKey);
  const now = await getRealNetworkNowSeconds();
  const START_BUFFER_SECONDS = 600;
  const STREAM_DURATION_SECONDS = 3600;
  const tx = await (client as any).create_stream(
    {
      sender: senderPublicKey,
      recipient,
      token: NATIVE_TOKEN_ID,
      total_amount: DEMO_STREAM_AMOUNT_STROOPS,
      start_time: BigInt(now + START_BUFFER_SECONDS),
      cliff_time: BigInt(now + START_BUFFER_SECONDS),
      end_time: BigInt(now + START_BUFFER_SECONDS + STREAM_DURATION_SECONDS),
      cancelable: true,
      proof: Buffer.from(REAL_RANGE_PROOF_BYTES),
      public_inputs: REAL_RANGE_PROOF_PUBLIC_INPUTS.map((b) => Buffer.from(b)),
    },
    { timeoutInSeconds: 1800 }
  );
  const sent = await tx.signAndSend();
  return sent.result as number;
}

export async function getRealStream(streamId: number): Promise<OnChainStream> {
  const client = await getClient(STREAM_CONTRACT_ID);
  const tx = await (client as any).get_stream({ stream_id: streamId });
  return tx.result as OnChainStream;
}

export async function getRealClaimableAmount(streamId: number): Promise<bigint> {
  const client = await getClient(STREAM_CONTRACT_ID);
  const tx = await (client as any).claimable_amount({ stream_id: streamId });
  return tx.result as bigint;
}
