// Real integration against the actual deployed Stellar testnet contracts — no mocking
// here. See deployments/testnet.json (repo root) for where these addresses come from and
// how to verify them independently on stellar.expert.
import { Client as ContractClient } from '@stellar/stellar-sdk/contract';
import freighter from '@stellar/freighter-api';

export const NETWORK_PASSPHRASE = 'Test SDF Network ; September 2015';
export const RPC_URL = 'https://soroban-testnet.stellar.org';

export const STREAM_CONTRACT_ID = 'CDEJZ5GPOW5GMDTBMJ2WD7ENPKHBPETZFUGAZ76QMDGHT5LNAEG5TKH7';
export const RANGE_PROOF_VERIFIER_ID = 'CARWCSIHZ7HCXDCCLRN2JX7SYDAKMZXI53M6AGUUXPRLLT3UJ3WIDLIY';
export const NATIVE_TOKEN_ID = 'CDLZFC3SYJYDZT7K67VZ75HPJVIEUVNIXF47ZG2FB2RMQQVU2HHGCYSC';

function hexToBytes(hex: string): Uint8Array {
  const out = new Uint8Array(hex.length / 2);
  for (let i = 0; i < out.length; i++) {
    out[i] = parseInt(hex.substring(i * 2, i * 2 + 2), 16);
  }
  return out;
}

// The one real, precomputed Groth16 proof this demo can submit today. Generated by an
// actual trusted-setup pipeline against the real range_proof.circom circuit — see
// ../circuits/README.md and ../circuits/build/range_proof/{proof.json,public.json}. It
// proves a FIXED amount (5,000,000 stroops = 0.5 XLM) is in range [1, 1_000_000_000].
// General-purpose in-browser proof generation (bundling the circuit's wasm witness
// calculator + snarkjs prover) is real future work, not attempted here — this demo can
// only create a stream of exactly this amount for now.
export const DEMO_STREAM_AMOUNT_STROOPS = 5_000_000n;
const REAL_RANGE_PROOF_HEX =
  '1576394dd31e3810dc98e1fd21ab18aedded58d5a5918eb8719e7285cc6f5c4613a756208462ceddbf4b4dcf46f3e8544b10f1838eb2de2ece5dba021d61a82b2543a7eb2ad496caa3ea17e29f0ff89ba9db63f69c12652d389a6ab584ee6d950e362741df18ca9ba3727de772be461afe17f79de97e562214892a5aeb3a4f592eded200fc7f792efbff1db16b68bffa910df19d68c244fb19812e109d43fb6516b288ee6ccde0aa211f20eb79553038b1c207e24517b791e125389beeb85040044a48c43d7df994c4d5faf4eb943e96dcc3247bfe6d0ee4437e0b11b814121d1d871314e79e7fbe0f9e1170749f441a8c68bfd7caf8ebfeb7ac76af49ba612b';
const REAL_RANGE_PROOF_PUBLIC_INPUTS_HEX = [
  '0000000000000000000000000000000000000000000000000000000000000001',
  '0000000000000000000000000000000000000000000000000000000000000001',
  '000000000000000000000000000000000000000000000000000000003b9aca00',
  '2a50431f0c3168c0be1bbb5405b319c02a868a696b208557af125d46fb3ab4f0',
];
export const REAL_RANGE_PROOF_BYTES = hexToBytes(REAL_RANGE_PROOF_HEX);
export const REAL_RANGE_PROOF_PUBLIC_INPUTS = REAL_RANGE_PROOF_PUBLIC_INPUTS_HEX.map(hexToBytes);

export class FreighterNotDetectedError extends Error {}

export async function connectWallet(): Promise<string> {
  const { isConnected, error: connErr } = await freighter.isConnected();
  if (connErr || !isConnected) {
    throw new FreighterNotDetectedError(
      'Freighter wallet extension not detected. Install it from freighter.app to use real wallet features.'
    );
  }
  const { address, error } = await freighter.requestAccess();
  if (error || !address) {
    throw new Error(error?.message ?? 'Wallet access was not granted.');
  }
  const { network, error: netErr } = await freighter.getNetwork();
  if (netErr) throw new Error(netErr.message ?? 'Could not read wallet network.');
  if (network !== 'TESTNET') {
    throw new Error(`Freighter is set to ${network}, but this app talks to Stellar testnet. Switch networks in Freighter.`);
  }
  return address;
}

async function getClient(contractId: string, publicKey?: string) {
  return ContractClient.from({
    contractId,
    networkPassphrase: NETWORK_PASSPHRASE,
    rpcUrl: RPC_URL,
    publicKey,
    signTransaction: freighter.signTransaction,
  });
}

/** Read-only: simulates a real call against the real deployed range_proof verifier with
 * the real proof above. No wallet signature needed — this is exactly the same call
 * `stellar contract invoke ... -- vrfy_prf --send=no` makes, just from the browser. */
export async function verifyRealProofOnChain(): Promise<boolean> {
  const client = await getClient(RANGE_PROOF_VERIFIER_ID);
  const tx = await (client as any).vrfy_prf({
    proof: Buffer.from(REAL_RANGE_PROOF_BYTES),
    public_inputs: REAL_RANGE_PROOF_PUBLIC_INPUTS.map((b) => Buffer.from(b)),
  });
  return tx.result as boolean;
}

export interface OnChainStream {
  sender: string;
  recipient: string;
  token: string;
  total_amount: bigint;
  withdrawn_amount: bigint;
  start_time: bigint;
  cliff_time: bigint;
  end_time: bigint;
  active: boolean;
  cancelable: boolean;
}

/** Real, live create_stream call against the real deployed stream contract, using the one
 * real proof this demo has. Requires a connected wallet — the transaction is genuinely
 * built, simulated, signed by Freighter, and submitted to testnet.
 *
 * start_time must be computed with a generous buffer, not a tight one: `Client.from()`
 * makes several sequential RPC round-trips (fetch contract instance, fetch wasm, parse
 * spec, simulate) before the transaction is even built, and then Freighter needs real
 * human time to review and approve. A 30-second buffer measured this failing — by the
 * time simulation actually ran, real elapsed time had already pushed the ledger's
 * timestamp past start_time, tripping create_stream's own "start_time in past" check
 * with no readable message (release wasm strips panic strings, so it surfaces as a bare
 * "UnreachableCodeReached" trap) — confirmed by reproducing it standalone against the
 * real contract outside the browser entirely, then fixing it the same way.
 */
export async function createRealDemoStream(senderPublicKey: string, recipient: string): Promise<number> {
  const client = await getClient(STREAM_CONTRACT_ID, senderPublicKey);
  const now = Math.floor(Date.now() / 1000);
  const START_BUFFER_SECONDS = 600;
  const STREAM_DURATION_SECONDS = 3600;
  const tx = await (client as any).create_stream(
    {
      sender: senderPublicKey,
      recipient,
      token: NATIVE_TOKEN_ID,
      total_amount: DEMO_STREAM_AMOUNT_STROOPS,
      start_time: BigInt(now + START_BUFFER_SECONDS),
      cliff_time: BigInt(now + START_BUFFER_SECONDS),
      end_time: BigInt(now + START_BUFFER_SECONDS + STREAM_DURATION_SECONDS),
      cancelable: true,
      proof: Buffer.from(REAL_RANGE_PROOF_BYTES),
      public_inputs: REAL_RANGE_PROOF_PUBLIC_INPUTS.map((b) => Buffer.from(b)),
    },
    // This governs the signed transaction ENVELOPE's own submission validity window — a
    // completely separate timeout from start_time above. AssembledTransaction.sign()
    // recomputes this window at the moment signing actually happens (not at build/
    // simulate time), so it has to cover real human review-and-approve time in Freighter's
    // popup, not just network latency. 30 seconds genuinely wasn't enough — confirmed by a
    // real submitted transaction failing with tx_too_late because the human took longer
    // than that to click approve.
    { timeoutInSeconds: 300 }
  );
  const sent = await tx.signAndSend();
  return sent.result as number;
}

export async function getRealStream(streamId: number): Promise<OnChainStream> {
  const client = await getClient(STREAM_CONTRACT_ID);
  const tx = await (client as any).get_stream({ stream_id: streamId });
  return tx.result as OnChainStream;
}

export async function getRealClaimableAmount(streamId: number): Promise<bigint> {
  const client = await getClient(STREAM_CONTRACT_ID);
  const tx = await (client as any).claimable_amount({ stream_id: streamId });
  return tx.result as bigint;
}
